/**
 * Bucket groups: `[category, four terms]`, in four bands that never share a day.
 * A day takes one group from each band (logic.ts), so terms that could pass for
 * another category sit in the same band as it. Every term is unique (tested).
 */
export const BANDS: string[][][] = [
  [
    ['Git subcommands', 'rebase', 'bisect', 'stash', 'reflog'],
    ['Unix text tools', 'grep', 'sed', 'awk', 'cut'],
    ['Shells', 'bash', 'zsh', 'fish', 'nushell'],
    ['Terminal editors', 'vim', 'emacs', 'nano', 'helix'],
    ['Container tools', 'docker', 'podman', 'kubectl', 'helm'],
    ['Package managers', 'npm', 'pip', 'cargo', 'brew'],
    ['Build tools', 'make', 'gradle', 'bazel', 'cmake'],
    ['CI services', 'jenkins', 'circleci', 'travis', 'buildkite'],
    ['SQL databases', 'postgres', 'mysql', 'sqlite', 'mariadb'],
    ['NoSQL stores', 'mongodb', 'redis', 'cassandra', 'dynamodb'],
    ['Message brokers', 'kafka', 'rabbitmq', 'nats', 'sqs'],
    ['Permission commands', 'chmod', 'chown', 'chgrp', 'umask'],
    ['Process commands', 'ps', 'top', 'kill', 'nice'],
    ['Network tools', 'curl', 'wget', 'ping', 'dig'],
    ['Linux distros', 'debian', 'fedora', 'arch', 'alpine'],
    ['Web servers', 'nginx', 'apache', 'caddy', 'traefik'],
    ['Compression', 'gzip', 'zstd', 'bzip2', 'xz'],
    ['Unix signals', 'SIGINT', 'SIGTERM', 'SIGKILL', 'SIGHUP'],
    ['Hash functions', 'sha256', 'md5', 'blake3', 'crc32'],
  ],
  [
    ['JS array methods', 'map', 'filter', 'reduce', 'flatMap'],
    ['Python keywords', 'lambda', 'yield', 'pass', 'nonlocal'],
    ['Derivable Rust traits', 'Clone', 'Debug', 'Default', 'PartialEq'],
    ['Go keywords', 'defer', 'chan', 'fallthrough', 'range'],
    ['C types', 'int', 'char', 'double', 'void'],
    ['Languages named for gems', 'Ruby', 'Perl', 'Crystal', 'Opal'],
    ['Languages named for people', 'Ada', 'Haskell', 'Pascal', 'Eiffel'],
    ['Languages named for places', 'Java', 'Kotlin', 'Ceylon', 'Delphi'],
    ['Lisp dialects', 'Clojure', 'Scheme', 'Racket', 'Fennel'],
    ['Access modifiers', 'public', 'private', 'protected', 'internal'],
    ['Jump statements', 'break', 'continue', 'return', 'goto'],
    ['Python built-ins', 'len', 'enumerate', 'isinstance', 'sorted'],
    ['TS utility types', 'Partial', 'Pick', 'Omit', 'Record'],
    ['SQL clauses', 'SELECT', 'WHERE', 'HAVING', 'GROUP BY'],
    ['JS falsy values', '0', 'NaN', 'null', 'undefined'],
    ['Haskell type classes', 'Functor', 'Monad', 'Monoid', 'Foldable'],
    ['C preprocessor', '#define', '#include', '#ifdef', '#pragma'],
    ['Python dunders', '__init__', '__repr__', '__eq__', '__iter__'],
    ['Python exceptions', 'TypeError', 'KeyError', 'ValueError', 'IndexError'],
    ['Rust smart pointers', 'Box', 'Rc', 'Arc', 'RefCell'],
  ],
  [
    ['HTTP methods', 'GET', 'POST', 'PUT', 'PATCH'],
    ['4xx status codes', '400', '401', '403', '404'],
    ['5xx status codes', '500', '502', '503', '504'],
    ['Well-known ports', '22', '80', '443', '5432'],
    ['React hooks', 'useState', 'useEffect', 'useRef', 'useMemo'],
    ['CSS display values', 'flex', 'grid', 'block', 'inline'],
    ['CSS position values', 'static', 'relative', 'absolute', 'sticky'],
    ['CSS units', 'px', 'em', 'rem', 'vh'],
    ['HTML void elements', 'br', 'img', 'input', 'hr'],
    ['Frontend frameworks', 'React', 'Vue', 'Svelte', 'Angular'],
    ['DNS record types', 'A', 'AAAA', 'CNAME', 'MX'],
    ['Auth standards', 'OAuth', 'JWT', 'SAML', 'OIDC'],
    ['Cookie attributes', 'HttpOnly', 'Secure', 'SameSite', 'Max-Age'],
    ['JS bundlers', 'webpack', 'rollup', 'esbuild', 'parcel'],
    ['JS runtimes', 'Node', 'Deno', 'Bun', 'QuickJS'],
    ['Browser storage', 'localStorage', 'IndexedDB', 'cookies', 'sessionStorage'],
    ['DOM events', 'click', 'keydown', 'submit', 'scroll'],
    ['Request headers', 'Accept', 'Host', 'Origin', 'Referer'],
    ['Transport protocols', 'TCP', 'UDP', 'QUIC', 'SCTP'],
    ['Image formats', 'PNG', 'WebP', 'AVIF', 'GIF'],
    ['Browser APIs', 'fetch', 'WebSocket', 'WebGL', 'WebRTC'],
    ['JS test runners', 'Jest', 'Vitest', 'Mocha', 'Playwright'],
  ],
  [
    ['Sorts, minus "sort"', 'quick', 'merge', 'heap', 'bubble'],
    ['Data structures', 'stack', 'queue', 'trie', 'deque'],
    ['Complexities', 'O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    ['Design patterns', 'singleton', 'factory', 'observer', 'adapter'],
    ['Scrum vocabulary', 'standup', 'retro', 'sprint', 'backlog'],
    ['Debugger actions', 'step into', 'step out', 'step over', 'breakpoint'],
    ['Units of data', 'nibble', 'byte', 'word', 'qword'],
    ['Sync primitives', 'mutex', 'semaphore', 'latch', 'barrier'],
    ['Graph algorithms', 'Dijkstra', 'A*', 'BFS', 'DFS'],
    ['Placeholder names', 'foo', 'bar', 'baz', 'qux'],
    ['Commit prefixes', 'feat', 'fix', 'chore', 'refactor'],
    ['Things that crash', 'segfault', 'deadlock', 'race', 'overflow'],
    ['___-driven development', 'TDD', 'BDD', 'DDD', 'FDD'],
    ['Logic gates', 'AND', 'OR', 'XOR', 'NAND'],
    ['Number bases', 'binary', 'octal', 'decimal', 'hex'],
    ['Cache eviction policies', 'LRU', 'LFU', 'FIFO', 'MRU'],
    ['Starts with "hot"', 'hotfix', 'hotkey', 'hotspot', 'hotswap'],
    ['Ends in "-ware"', 'firmware', 'malware', 'middleware', 'shareware'],
    ['Computing pioneers', 'Turing', 'Hopper', 'Knuth', 'Lovelace'],
    ['Text encodings', 'UTF-8', 'ASCII', 'Base64', 'EBCDIC'],
    ['Formatters & linters', 'eslint', 'prettier', 'black', 'rustfmt'],
  ],
]

